/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#00424e",
        "background": "#121319",
        "tertiary-fixed": "#ffd9e4",
        "on-secondary-fixed-variant": "#004e5c",
        "on-error": "#690005",
        "outline": "#958ea0",
        "on-tertiary": "#640039",
        "surface-container-lowest": "#0d0e14",
        "on-tertiary-fixed": "#3e0022",
        "secondary-fixed-dim": "#4cd7f6",
        "on-tertiary-fixed-variant": "#8c0053",
        "surface-container": "#1e1f26",
        "inverse-surface": "#e3e1eb",
        "primary": "#d0bcff",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#ffb0cd",
        "surface-container-highest": "#34343b",
        "on-primary-fixed-variant": "#5516be",
        "surface-container-low": "#1a1b22",
        "on-primary-fixed": "#23005c",
        "inverse-primary": "#6d3bd7",
        "secondary-fixed": "#acedff",
        "error-container": "#93000a",
        "secondary": "#4cd7f6",
        "on-primary": "#3c0091",
        "tertiary": "#ffb0cd",
        "on-primary-container": "#340080",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#d0bcff",
        "on-secondary": "#003640",
        "inverse-on-surface": "#2f3037",
        "surface-bright": "#383940",
        "on-surface": "#e3e1eb",
        "on-background": "#e3e1eb",
        "on-secondary-fixed": "#001f26",
        "surface": "#121319",
        "surface-container-high": "#292930",
        "primary-container": "#a078ff",
        "on-tertiary-container": "#570032",
        "secondary-container": "#03b5d3",
        "on-error-container": "#ffdad6",
        "surface-variant": "#34343b",
        "on-surface-variant": "#cbc3d7",
        "tertiary-container": "#f751a1",
        "surface-tint": "#d0bcff",
        "outline-variant": "#494454",
        "surface-dim": "#121319"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "gutter-desktop": "1.5rem",
        "space-sm": "0.5rem",
        "margin-desktop": "2rem",
        "gutter": "1rem",
        "space-xl": "2rem",
        "margin": "1rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "metric-display": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-lg": ["13px", {"lineHeight": "18px", "fontWeight": "500"}],
        "metric-display": ["32px", {"lineHeight": "38px", "fontWeight": "700"}],
        "headline-lg-mobile": ["22px", {"lineHeight": "30px", "fontWeight": "600"}],
        "label-md": ["11px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["10px", {"lineHeight": "14px", "fontWeight": "600"}],
        "headline-xl-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "body-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "headline-xl": ["36px", {"lineHeight": "44px", "fontWeight": "700"}],
        "headline-lg": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
