/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#67e8f9",
        "background": "#09090B",
        "tertiary-fixed": "#e2e8f0",
        "on-secondary-fixed-variant": "#0e7490",
        "on-error": "#690005",
        "outline": "#71717A",
        "on-tertiary": "#0f172a",
        "surface-container-lowest": "#09090B",
        "on-tertiary-fixed": "#0f172a",
        "secondary-fixed-dim": "#0891b2",
        "on-tertiary-fixed-variant": "#334155",
        "surface-container": "#18181B",
        "inverse-surface": "#F4F4F5",
        "primary": "#06b6d4",
        "error": "#f87171",
        "tertiary-fixed-dim": "#94a3b8",
        "surface-container-highest": "#27272A",
        "on-primary-fixed-variant": "#0891b2",
        "surface-container-low": "#121316",
        "on-primary-fixed": "#083344",
        "inverse-primary": "#0891b2",
        "secondary-fixed": "#22d3ee",
        "error-container": "#450a0a",
        "secondary": "#06b6d4",
        "on-primary": "#082f49",
        "tertiary": "#94a3b8",
        "on-primary-container": "#67e8f9",
        "primary-fixed": "#a5f3fc",
        "primary-fixed-dim": "#67e8f9",
        "on-secondary": "#082f49",
        "inverse-on-surface": "#18181B",
        "surface-bright": "#27272A",
        "on-surface": "#F4F4F5",
        "on-background": "#F4F4F5",
        "on-secondary-fixed": "#083344",
        "surface": "#09090B",
        "surface-container-high": "#222328",
        "primary-container": "#083344",
        "on-tertiary-container": "#f1f5f9",
        "secondary-container": "#083344",
        "on-error-container": "#fecaca",
        "surface-variant": "#27272A",
        "on-surface-variant": "#A1A1AA",
        "tertiary-container": "#1e293b",
        "surface-tint": "#06b6d4",
        "outline-variant": "#3F3F46",
        "surface-dim": "#09090B"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "gutter-desktop": "1.5rem",
        "space-sm": "0.5rem",
        "margin-desktop": "2rem",
        "gutter": "1rem",
        "space-xl": "2rem",
        "margin": "1rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "metric-display": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-lg": ["13px", {"lineHeight": "18px", "fontWeight": "500"}],
        "metric-display": ["32px", {"lineHeight": "38px", "fontWeight": "700"}],
        "headline-lg-mobile": ["22px", {"lineHeight": "30px", "fontWeight": "600"}],
        "label-md": ["11px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["10px", {"lineHeight": "14px", "fontWeight": "600"}],
        "headline-xl-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "body-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "headline-xl": ["36px", {"lineHeight": "44px", "fontWeight": "700"}],
        "headline-lg": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
